### ISSUE TITLE
Warning in origRenderFunc()

### ISSUE THREAD

**Issue by anfederico** [compbiomed/PathoStat#12]
This is not really an issue, but it would be good to suppress warnings like this.

```
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "3c4e495404ba"; Shiny doesn't use them
```

This errors stems from the plotly graphs. We can fix it by applying this line to each plotly graph. We should do this after fixing other bugs though.

```R
p <- plot_ly(...)
p$elementId <- NULL # To suppress a shiny warning
return(p)
```

**Comment by jasonzhao0307** [comment]
Yeah, I will fix it.
