### ISSUE TITLE
heatmap and boxplot in beta diversity

### ISSUE THREAD

**Issue by jasonzhao0307** [compbiomed/PathoStat#14]
We could also change the beta diversity heatmap to the same type we have in relative abundance.

**Comment by anfederico** [comment]
Yeah I think so, will try to do this!

**Comment by jasonzhao0307** [comment]
After adding this feature (and also in the future), make sure go to utils/old_server_stuff.R, and add a updateSelectInput() part in the updateCovariate() function for the condition handle in that plot (as we need to update the conditions once we upload new datasets, instead of using the pre-loaded example dataset). I've added those handles for the RA barplot and heatmap.

**Comment by anfederico** [comment]
Okay, will do, and thanks!

**Comment by jasonzhao0307** [comment]
boxplot also needs modifying

**Comment by anfederico** [comment]
Separate plotting of heatmap from the boxplot functionality
