### ISSUE TITLE
Issue changing taxon level on some plots

### ISSUE THREAD

**Issue by anfederico** [compbiomed/PathoStat#16]
Getting ```Error: invalid subscript type 'list'``` when changing taxlev from no rank. Happens in a few plots. You can reproduce the error in the alpha/diversity charts.

<img width="925" alt="screen shot 2018-06-25 at 10 39 40 am" src="https://user-images.githubusercontent.com/18452646/41856898-3429e028-7864-11e8-883d-d397023459f6.png">

**Comment by jasonzhao0307** [comment]
It works normally on my computer (I'm using the current version on compbiomed/PathoStat).

**Comment by anfederico** [comment]
Working now.
