### ISSUE TITLE
Replacing ggvis with plotly for Relative Abundance Plots

### ISSUE THREAD

**Issue by anfederico** [compbiomed/PathoStat#2]
Here is a working example

```R
# In the original plot.relative.abundance function()
taxdata <- findTaxData()

# samples x organisms
df.ra <- as.data.frame(t(taxdata), stringAsFactors = FALSE)

# Order samples by a selected condition
covariates.tmp <- colnames(sample_data(pstat))
covariates.smp <- pstat@sam_data@.Data[[which(covariates.tmp %in% input$select_condition)]]
rownames(df.ra) <- paste(covariates.smp, rownames(df.ra), sep="_")

# Reorder by filter
df.ra <- df.ra[order(covariates.smp),]

# Reorder by most prominent organisms
df.ra <- df.ra[,order(colSums(df.ra))]

df.ra$samples <- rownames(df.ra)
p <- plot_ly(df.ra,
            y = ~samples, 
            x = df.ra[[colnames(df.ra)[1]]], 
            type = 'bar', orientation = 'h', 
            name = substr(colnames(df.ra)[1], 1, 30)) %>%
  layout(font = list(size = 8),
         yaxis = list(title = '', 
                       tickmode = "array",
                       tickvals = rownames(df.ra),
                       ticktext = paste(sapply(strsplit(rownames(df.ra), "_"), function(x) x[[1]]), " "),
                       showticklabels = TRUE,
                       categoryorder = 'trace'),
         xaxis = list(title = 'Relative Abundance'),
         barmode = 'stack')
for (i in 2:ncol(df.ra)-1) {
  p <- add_trace(p, x = df.ra[[colnames(df.ra)[i]]], 
                name = substr(colnames(df.ra)[i], 1, 30))
}
p
```

Here is a screenshot. It has hovering capabilities and some other bells and whistles offered by plotly.

<img width="579" alt="screen shot 2018-06-06 at 3 09 00 pm" src="https://user-images.githubusercontent.com/18452646/41059811-a4b17554-699b-11e8-8bc3-4a90b8abec64.png">

**Comment by wevanjohnson** [comment]
See below: 


> On Jun 9, 2018, at 1:25 PM, Anthony Federico <notifications@github.com> wrote:
> 
> Yes you can hover to see relative abundance, organism, and sample
Awesome!
> We could definitely add an option to remove the key on the right for hovering only
Okay, do it. Just add a checkbox to remove/add the key
> Right now df.ra <- df.ra[,order(colSums(df.ra))] sorts by microbe frequency so that the organism that appears most across all samples is listed first
Cool, yes this basically what I want. However, in addition to this, give a box that allows the user to choose the sort the order, i.e. lets say I wanted the display order (in the bars) to be mycobacterium (TB), then streptococcus, then ordered by most often? Also, could I then order the samples (not microbes in the bars, but the bars themselves) by increasing/decreasing TB, strep, etc?  
> By color bars do you mean something like {Col/Row}SideColors?
Exactly. Imagine this: I have TB/control samples from nose, mouth, sputum. I sort the samples up/down, first by TB, strep, etc prevalence. Then I put a colored sidebar (on either side) that indicates TB/control status, and then another sidebar that indicates tissue type. And allow me to do this at the species, genus, …, phylum, etc levels, all interactively. This would be an amazing tool for exploring datasets!

**Comment by wevanjohnson** [comment]
Also, one more item on my wish list: another tab that displays a bar and table summary for the average profile. (Anthony, you had this in your TB database). Allow for a single bar/table that summarizes all the samples, and then also allow to make summary bars stratified by different groups, i.e. in the TB/nasal/oral/sputum example, allow to get a bar/table for TB vs. control or nasal vs. oral vs. sputum, or even TB/control separately within nasal, oral, sputum.   

Does this make sense?

**Comment by anfederico** [comment]
@wevanjohnson I have this working isolated outside PathoStat, however I am using a pstat object so it should be pretty easy to integrate. Couldn't get Shiny to publish due to some dependency issues so I made a video instead.

How's this look?

https://streamable.com/6yiyr
