### ISSUE TITLE
Comment characters?

### ISSUE THREAD

**Issue by wevanjohnson** [compbiomed/PathoStat#5]
Hey, I'm getting an error reading in my PathoScope files. For examples, for one file I get the following error: 

 Error: line 858 did not have 11 elements

Looking at this line, it seems that this is a comment character issue, i.e. line 858 looks like this:

ti|931890|org|Eremothecium_cymbalariae_DBVPG#7215

However, I could not seem to solve this myself. I thought you already deal with this? I saw this in the code, utils.R:

  # Read all reports into list
    mlist <- lapply(reportfiles, function(rf){
    read.table(rf, sep='\t', header=TRUE, stringsAsFactors=FALSE,
    row.names=1, skip=1, comment.char="")
    })

So isn't this already changing the comment character away from "#" to being ""? What am I missing?

**Comment by anfederico** [comment]
I tried to reproduce the error and the `comment.char=""` handles the comment character correctly. The parameters in that read.table will handle `ti|931890|org|Eremothecium_cymbalariae_DBVPG#7215` as a row name correctly, so it might be something else? 

Could you post lines 1-5 and 855-860?

Edit: There is a bug. The function `loadPathoscopeReports` in utils.R is not currently being used in the server.R code. Files are being read explicitly and the `comment.char=""` option is not used. Easy fix.
