### ISSUE TITLE
use plotly for heatmap 

### ISSUE THREAD

**Issue by jasonzhao0307** [compbiomed/PathoStat#8]
We have 2 heatmaps now, one under Relative abundance tab, one under Diversity/beta diversity tab. It would be better if we could use plotly for that?

**Comment by anfederico** [comment]
Will take a look

**Comment by jasonzhao0307** [comment]
It would be cool to support the option of adding multiple variable color bars

**Comment by jasonzhao0307** [comment]
Looks good!
